### ISSUE TITLE
Slow loading mdct Studio

### ISSUE THREAD

**Issue by mdctgroup** [mdctgroup/Buglist-Wish-List#15]
Slow loading of mdct Studio since Release 36.

**Comment by mdctgroup** [comment]
Problem was improved in release 37.
Still being processed.

**Comment by 25space** [comment]
[LOW CASE]

**Comment by 25space** [comment]
Cloud Studio former "mdct Studio" was terminated with an update on 02.06.2020.

Article:
https://25space.com/magazine/change-termination-of-cloud-studio/
